delete from advice_master;
insert into advice_master (`advice_type`,`advice_sub_type`, `advice_desc`) Values('ocular_pre_surgery','Cataract Surgery','Cataract surgery advised to the patient');
insert into advice_master (`advice_type`,`advice_sub_type`, `advice_desc`) Values('ocular_pre_surgery','Glaucoma Surgery','Glaucoma surgery advised to the patient');
insert into advice_master (`advice_type`,`advice_sub_type`, `advice_desc`) Values('ocular_pre_surgery','DCR Surgery','DCR surgery advised to the patient');
insert into advice_master (`advice_type`,`advice_sub_type`, `advice_desc`) Values('ocular_pre_surgery','Pterygium Surgery','Pterygium surgery advised to the patient');
insert into advice_master (`advice_type`,`advice_sub_type`, `advice_desc`) Values('ocular_post_surgery','No head bath','Advised not to take head bath');
insert into advice_master (`advice_type`,`advice_sub_type`, `advice_desc`) Values('ocular_post_surgery','Avoid reading','');
insert into advice_master (`advice_type`,`advice_sub_type`, `advice_desc`) Values('ocular_post_surgery','Avoid television','');
insert into advice_master (`advice_type`,`advice_sub_type`, `advice_desc`) Values('ocular_post_surgery','Wear dark glasses','');
insert into advice_master (`advice_type`,`advice_sub_type`, `advice_desc`) Values('ocular_post_surgery','No light exposure','');
delete from complaint_master;
insert into complaint_master (`complaint_type`,`complaint_sub_type`, `complaint_desc`) Values('ocular','Redness','Redness in eyes');
insert into complaint_master (`complaint_type`,`complaint_sub_type`, `complaint_desc`) Values('ocular','Pain','Pain in eyes');
insert into complaint_master (`complaint_type`,`complaint_sub_type`, `complaint_desc`) Values('ocular','Watering','Watery eyes');
insert into complaint_master (`complaint_type`,`complaint_sub_type`, `complaint_desc`) Values('ocular','Dryness','Dryness in eyes');
insert into complaint_master (`complaint_type`,`complaint_sub_type`, `complaint_desc`) Values('ocular','Diminished Vision','Diminished Vision');
insert into complaint_master (`complaint_type`,`complaint_sub_type`, `complaint_desc`) Values('ocular','Blurred Vision','Blurred Vision');
insert into complaint_master (`complaint_type`,`complaint_sub_type`, `complaint_desc`) Values('ocular','Broken Spectacle','Broken Spectacle');
insert into complaint_master (`complaint_type`,`complaint_sub_type`, `complaint_desc`) Values('','Defective vision for distance','');
delete from patient_prescription_record;
delete from medical_prescriptions_master;
delete from diagnosis_master;
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('ocular','Conjunctiva_Acute Conjunctivitis','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('general','Conjunctiva_Allergic Conjunctivitis','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Conjunctiva_Bitot Spots','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Conjunctiva_Bleb','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Conjunctiva_Chemosis','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Conjunctiva_Ciliary congestion','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Conjunctiva_Concretions','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Conjunctiva_Bulbar','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Conjunctiva_Fornices','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Conjunctiva_Palpebral','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Conjunctiva_Conjunctivital flap in situ','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Conjunctiva_Cyst','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Conjunctiva_Dermoid','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Conjunctiva_Dermolipoma','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Conjunctiva_Discharge','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Conjunctiva_Epithelioma','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Conjunctiva_Follicles','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Conjunctiva_Foreign Body','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Conjunctiva_Giant Pupillary Conjunctivitis','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Conjunctiva_Melanosis','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Conjunctiva_Neavus','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Conjunctiva_Normal','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Conjunctiva_Pale','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Conjunctiva_Papillae','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Conjunctiva_Pseudo Membranous Conjuctivitis','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Conjunctiva_Phlycten','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Conjunctiva_Pingecula','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Conjunctiva_Pterygium','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Conjunctiva_Psudeo membranes','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Conjunctiva_Pingecula Inflamed','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Cornea_Pterygium','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Cornea_Dry Eye Disease','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Cornea_Keratomalacia','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Cornea_Recurrent Corneal Erosion Syndrome','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Cornea_Bullous Keratopathy','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Cornea_Filamentry Keratopathy','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Cornea_Neurotrophic Keratisis','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Cornea_Toxic keratopathy','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Cornea_Fungal Keratisis','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Cornea_Acanthamoeba Keratisis','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Cornea_Herpes Simplex Virus Keratopathy','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Cornea_Marginal Keratisis','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Cornea_Interstitial Keratisis','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Cornea_Peripheral Ulcerative Keratisis','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Cornea_Pellucid Marginal Degeneration','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Cornea_Stromal Dystrophies','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Cornea_Fuchs Endothelial Dystrophy','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Cornea_Keratoconus','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Cornea_Band -Shaped Keratopathy','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Cornea_Keratisis Medicamentosa','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Cornea_Chemical injury','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Cornea_Corneal changes in Contact Lens users','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Cornea_Corneal Graft Infection','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Cornea_Graft Rejection','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Sclera_Episcleritis','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Sclera_Scleritis','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','External Disease_Trichiasis','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','External Disease_Chalazion','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','External Disease_Stye','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','External Disease_Blepharitis','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','External Disease_Lagopthalmos','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','External Disease_Exposure Keratopathy','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','External Disease_Ocular Surface Suquamous Neoplasia','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','External Disease_Allergic Conjunctivitis','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','External Disease_Bacterial Conjunctivitis','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Lens_Cataract','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Lens_Posterior Subcapsular Cataract','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Lens_Anterior Subcapsuar Cataract','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Lens_Psudeo Phakia Cataract','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Lens_Mature Cataract','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Lens_Hyper Mature Cataract','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Lens_Morgagian Cataract','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Lens_Phaco Donesis Cataract','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Lens_ Ectopia Lentis Cataract','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Lens_ Aphakia Cataract','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','Lens_ Dislocated IOL Cataract','');
insert into diagnosis_master (`diagnosis_type`,`diagnosis_sub_type`, `diagnosis_desc`) Values('','','');
delete from instructions_master;
insert into instructions_master (`instruction_type`,`instruction_sub_type`, `instruction_desc`) Values('general','Regular follow up','');
insert into instructions_master (`instruction_type`,`instruction_sub_type`, `instruction_desc`) Values('general','Regular medication','');
insert into instructions_master (`instruction_type`,`instruction_sub_type`, `instruction_desc`) Values('general','Call in case of emergency','');
insert into instructions_master (`instruction_type`,`instruction_sub_type`, `instruction_desc`) Values('general','Keep all documents handy','');
insert into instructions_master (`instruction_type`,`instruction_sub_type`, `instruction_desc`) Values('general','Avoid Headbath','');
insert into instructions_master (`instruction_type`,`instruction_sub_type`, `instruction_desc`) Values('general','Dont Sleep On Side Of Operated Eye','');
insert into instructions_master (`instruction_type`,`instruction_sub_type`, `instruction_desc`) Values('general','Avoid Spicy Food','');
insert into instructions_master (`instruction_type`,`instruction_sub_type`, `instruction_desc`) Values('general','Avoid Playing With Children','');
insert into instructions_master (`instruction_type`,`instruction_sub_type`, `instruction_desc`) Values('general','Avoid Rubbing Eyes','');
insert into instructions_master (`instruction_type`,`instruction_sub_type`, `instruction_desc`) Values('general','Dont Watch TV,Computer for 8 Days','');
insert into instructions_master (`instruction_type`,`instruction_sub_type`, `instruction_desc`) Values('general','Avoid Reading For 8 Days','');
insert into instructions_master (`instruction_type`,`instruction_sub_type`, `instruction_desc`) Values('general','Avoid Exposure To Sunlight','');
delete from investigations_master;
insert into investigations_master (`investigation_type`,`investigation_sub_type`, `investigation_desc`) Values('ocular','A Scan','For IOL calculation');
insert into investigations_master (`investigation_type`,`investigation_sub_type`, `investigation_desc`) Values('ocular','B Scan','Retinal Pathology');
insert into investigations_master (`investigation_type`,`investigation_sub_type`, `investigation_desc`) Values('ocular','IOL master','Axial lengh IOL calculation');
insert into investigations_master (`investigation_type`,`investigation_sub_type`, `investigation_desc`) Values('ocular','Gonioscopy','Study of angles');
insert into investigations_master (`investigation_type`,`investigation_sub_type`, `investigation_desc`) Values('ocular','Cornial Topography','Assesment of corneal pathology');
insert into investigations_master (`investigation_type`,`investigation_sub_type`, `investigation_desc`) Values('ocular','Fundus Photo','Visualisation of fundus');
insert into investigations_master (`investigation_type`,`investigation_sub_type`, `investigation_desc`) Values('ocular','OCT','Study of retina macula anterior segment pathology');
insert into investigations_master (`investigation_type`,`investigation_sub_type`, `investigation_desc`) Values('ocular','Perimetry','Visual field study');
insert into investigations_master (`investigation_type`,`investigation_sub_type`, `investigation_desc`) Values('ocular','Schiots Tonometry','IOP measurement');
insert into investigations_master (`investigation_type`,`investigation_sub_type`, `investigation_desc`) Values('ocular','Non Contact tonometry','IOP measurement');
insert into investigations_master (`investigation_type`,`investigation_sub_type`, `investigation_desc`) Values('ocular','Pachymetry','Corneal thickness measurement');
insert into investigations_master (`investigation_type`,`investigation_sub_type`, `investigation_desc`) Values('ocular','Schirms Test','Dryness Assesments');
insert into investigations_master (`investigation_type`,`investigation_sub_type`, `investigation_desc`) Values('ocular','Flurosciene Stain','Epithelial defect');
insert into investigations_master (`investigation_type`,`investigation_sub_type`, `investigation_desc`) Values('ocular','Cover Test','Squint evaluation');
insert into investigations_master (`investigation_type`,`investigation_sub_type`, `investigation_desc`) Values('ocular','Prism Test','Squint evaluation');
insert into investigations_master (`investigation_type`,`investigation_sub_type`, `investigation_desc`) Values('ocular','Corneal Reflects','Squint evaluation');
insert into investigations_master (`investigation_type`,`investigation_sub_type`, `investigation_desc`) Values('ocular','FFA','Retinal Vessel Pathology');
insert into investigations_master (`investigation_type`,`investigation_sub_type`, `investigation_desc`) Values('ocular','ICG','Retinal Vessel Pathology');
insert into investigations_master (`investigation_type`,`investigation_sub_type`, `investigation_desc`) Values('ocular','Optical Biometry','IOL ,Axial lengthmeasurement');
delete from minor_opd_procedures_master;
insert into procedures_master (`procedure_type`,`procedure_sub_type`, `procedure_desc`) Values('ocular','Refraction','');
insert into procedures_master (`procedure_type`,`procedure_sub_type`, `procedure_desc`) Values('ocular','Gonioscopy','');
insert into procedures_master (`procedure_type`,`procedure_sub_type`, `procedure_desc`) Values('ocular','Pachymetry','');
insert into procedures_master (`procedure_type`,`procedure_sub_type`, `procedure_desc`) Values('ocular','Fundus fluroscein angiography','');
insert into procedures_master (`procedure_type`,`procedure_sub_type`, `procedure_desc`) Values('ocular','Suture removal','');
insert into procedures_master (`procedure_type`,`procedure_sub_type`, `procedure_desc`) Values('ocular','Cleaning and dressing','');
insert into procedures_master (`procedure_type`,`procedure_sub_type`, `procedure_desc`) Values('ocular','Dialated','');
insert into procedures_master (`procedure_type`,`procedure_sub_type`, `procedure_desc`) Values('ocular','Dialated Examination','');
delete from special_precautions_master;
insert into special_precautions_master (`precaution_type`,`precaution_sub_type`, `precaution_desc`) Values('general','','Compulsory bed rest');
insert into special_precautions_master (`precaution_type`,`precaution_sub_type`, `precaution_desc`) Values('general','','Pop up position');
insert into special_precautions_master (`precaution_type`,`precaution_sub_type`, `precaution_desc`) Values('general','','Dark glasses');
insert into special_precautions_master (`precaution_type`,`precaution_sub_type`, `precaution_desc`) Values('general','','One eyed patient');
insert into special_precautions_master (`precaution_type`,`precaution_sub_type`, `precaution_desc`) Values('general','','Hypertensive Retinopathy');
insert into special_precautions_master (`precaution_type`,`precaution_sub_type`, `precaution_desc`) Values('general','','Diabetic Retinopathy');
insert into special_precautions_master (`precaution_type`,`precaution_sub_type`, `precaution_desc`) Values('general','','Systemic Disorders ');